# ============================================
# File: manifests/services/mysql-service.yaml
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wordpress-mysql-app
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP

---
